spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservationdb
    username: root
    password: USAdream$123
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true      